file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/X11")
file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/patches/ks_tables.h" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/X11")

check_include_file("dlfcn.h" HAVE_DLFCN_H)
check_include_file("dl.h" HAVE_DL_H)
check_include_file("inttypes.h" HAVE_INTTYPES_H)
check_include_file("sys/filio.h" HAVE_SYS_FILIO_H)
check_include_file("sys/ioctl.h" HAVE_SYS_IOCTL_H)
check_include_file("sys/select.h" HAVE_SYS_SELECT_H)
check_include_file("sys/socket.h" HAVE_SYS_SELECT_H)
check_include_file("sys/unistd.h" HAVE_UNISTD_H)
check_function_exists("getresuid" HASGETRESUID)
#check_function_exists("issetugid" HASSETUGID)
check_function_exists("shmat" HAS_SHM)
check_function_exists("reallocarray" HAVE_REALLOCARRAY)
check_function_exists("seteuid" HAVE_SETEUID)
check_function_exists("seteuid" HAVE_SETEUID)
check_function_exists("__builtin_popcountl" HAVE___BUILTIN_POPCOUNTL)
check_function_exists("mblen" HAVE_MBLEN)

file(CONFIGURE
        OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/X11/config.h"
        CONTENT "
#pragma once
// #define COMPOSECACHE 1
// #cmakedefine HASGETRESUID
// #cmakedefine HASSETUGID
#cmakedefine HAS_SHM
#cmakedefine HAVE_DLFCN_H
#cmakedefine HAVE_DL_H
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_REALLOCARRAY
#cmakedefine HAVE_SETEUID
#cmakedefine HAVE_SYS_FILIO_H
#cmakedefine HAVE_SYS_IOCTL_H
#cmakedefine HAVE_SYS_SELECT_H
#cmakedefine HAVE_SYS_SOCKET_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE___BUILTIN_POPCOUNTL
/* #undef NO_XLOCALEDIR */
/* #undef LOCALCONN */
#define TCPCONN 1
#define UNIXCONN 1
#define USE_DYNAMIC_XCURSOR 1
#define USE_POLL 1

#define USE_THREAD_SAFETY_CONSTRUCTOR 1
#define X11_DATADIR \"/usr/share/X11\"
#define X11_LIBDIR \"/usr/lib/X11\"
#define XCMS 1
#define XERRORDB \"/usr/share/X11/XErrorDB\"
#define XF86BIGFONT 1
#define XKB 1
#define XKEYSYMDB \"/usr/share/X11/XKeysymDB\"
#define XLOCALE 1
#define XLOCALEDATADIR \"/usr/share/X11/locale\"
#define XLOCALEDIR \"/usr/share/X11/locale\"
#define XLOCALELIBDIR \"/usr/lib/X11/locale\"
#define XTHREADS 1
#define XUSE_MTSAFE_API 1
#define TRANS_CLIENT
#define XIM_t

#ifndef HAVE_MBLEN
#include <unistd.h>
#include <stdlib.h>
#define mblen mblen_static
__attribute__((__unused__))
static int mblen_static(const char *s, size_t n) {
    return mbtowc(0, s, n);
}
#endif")

add_library(X11 STATIC
        "libx11/src/AllCells.c"
        "libx11/src/AllowEv.c"
        "libx11/src/AllPlanes.c"
        "libx11/src/AutoRep.c"
        "libx11/src/Backgnd.c"
        "libx11/src/BdrWidth.c"
        "libx11/src/Bell.c"
        "libx11/src/Border.c"
        "libx11/src/ChAccCon.c"
        "libx11/src/ChActPGb.c"
        "libx11/src/ChClMode.c"
        "libx11/src/ChCmap.c"
        "libx11/src/ChGC.c"
        "libx11/src/ChKeyCon.c"
        "libx11/src/ChkIfEv.c"
        "libx11/src/ChkMaskEv.c"
        "libx11/src/ChkTypEv.c"
        "libx11/src/ChkTypWEv.c"
        "libx11/src/ChkWinEv.c"
        "libx11/src/ChPntCon.c"
        "libx11/src/ChProp.c"
        "libx11/src/ChSaveSet.c"
        "libx11/src/ChWAttrs.c"
        "libx11/src/ChWindow.c"
        "libx11/src/CirWin.c"
        "libx11/src/CirWinDn.c"
        "libx11/src/CirWinUp.c"
        "libx11/src/ClDisplay.c"
        "libx11/src/ClearArea.c"
        "libx11/src/Clear.c"
        "libx11/src/ConfWind.c"
        "libx11/src/Context.c"
        "libx11/src/ConvSel.c"
        "libx11/src/CopyArea.c"
        "libx11/src/CopyCmap.c"
        "libx11/src/CopyGC.c"
        "libx11/src/CopyPlane.c"
        "libx11/src/CrBFData.c"
        "libx11/src/CrCmap.c"
        "libx11/src/CrCursor.c"
        "libx11/src/CrGC.c"
        "libx11/src/CrGlCur.c"
        "libx11/src/CrPFBData.c"
        "libx11/src/CrPixmap.c"
        "libx11/src/CrWindow.c"
        "libx11/src/Cursor.c"
        "libx11/src/DefCursor.c"
        "libx11/src/DelProp.c"
        "libx11/src/Depths.c"
        "libx11/src/DestSubs.c"
        "libx11/src/DestWind.c"
        "libx11/src/DisName.c"
        "libx11/src/DrArc.c"
        "libx11/src/DrArcs.c"
        "libx11/src/DrLine.c"
        "libx11/src/DrLines.c"
        "libx11/src/DrPoint.c"
        "libx11/src/DrPoints.c"
        "libx11/src/DrRect.c"
        "libx11/src/DrRects.c"
        "libx11/src/DrSegs.c"
        "libx11/src/ErrDes.c"
        "libx11/src/ErrHndlr.c"
        "libx11/src/evtomask.c"
        "libx11/src/EvToWire.c"
        "libx11/src/FetchName.c"
        "libx11/src/FillArc.c"
        "libx11/src/FillArcs.c"
        "libx11/src/FillPoly.c"
        "libx11/src/FillRct.c"
        "libx11/src/FillRcts.c"
        "libx11/src/FilterEv.c"
        "libx11/src/Flush.c"
        "libx11/src/Font.c"
        "libx11/src/FontInfo.c"
        "libx11/src/FontNames.c"
        "libx11/src/FreeCmap.c"
        "libx11/src/FreeCols.c"
        "libx11/src/FreeCurs.c"
        "libx11/src/FreeEData.c"
        "libx11/src/FreeEventData.c"
        "libx11/src/FreeGC.c"
        "libx11/src/FreePix.c"
        "libx11/src/FSSaver.c"
        "libx11/src/FSWrap.c"
        "libx11/src/GCMisc.c"
        "libx11/src/Geom.c"
        "libx11/src/GetAtomNm.c"
        "libx11/src/GetColor.c"
        "libx11/src/GetDflt.c"
        "libx11/src/GetEventData.c"
        "libx11/src/GetFPath.c"
        "libx11/src/GetFProp.c"
        "libx11/src/GetGCVals.c"
        "libx11/src/GetGeom.c"
        "libx11/src/GetHColor.c"
        "libx11/src/GetHints.c"
        "libx11/src/GetIFocus.c"
        "libx11/src/GetImage.c"
        "libx11/src/GetKCnt.c"
        "libx11/src/GetMoEv.c"
        "libx11/src/GetNrmHint.c"
        "libx11/src/GetPCnt.c"
        "libx11/src/GetPntMap.c"
        "libx11/src/GetProp.c"
        "libx11/src/GetRGBCMap.c"
        "libx11/src/GetSOwner.c"
        "libx11/src/GetSSaver.c"
        "libx11/src/GetStCmap.c"
        "libx11/src/GetTxtProp.c"
        "libx11/src/GetWAttrs.c"
        "libx11/src/GetWMCMapW.c"
        "libx11/src/GetWMProto.c"
        "libx11/src/globals.c"
        "libx11/src/GrButton.c"
        "libx11/src/GrKeybd.c"
        "libx11/src/GrKey.c"
        "libx11/src/GrPointer.c"
        "libx11/src/GrServer.c"
        "libx11/src/Host.c"
        "libx11/src/Iconify.c"
        "libx11/src/IfEvent.c"
        "libx11/src/imConv.c"
        "libx11/src/ImText16.c"
        "libx11/src/ImText.c"
        "libx11/src/ImUtil.c"
        "libx11/src/InitExt.c"
        "libx11/src/InsCmap.c"
        "libx11/src/IntAtom.c"
        "libx11/src/KeyBind.c"
        "libx11/src/KeysymStr.c"
        "libx11/src/KillCl.c"
        "libx11/src/LiHosts.c"
        "libx11/src/LiICmaps.c"
        "libx11/src/LiProps.c"
        "libx11/src/ListExt.c"
        "libx11/src/LoadFont.c"
        "libx11/src/LockDis.c"
        "libx11/src/locking.c"
        "libx11/src/LookupCol.c"
        "libx11/src/LowerWin.c"
        "libx11/src/Macros.c"
        "libx11/src/MapRaised.c"
        "libx11/src/MapSubs.c"
        "libx11/src/MapWindow.c"
        "libx11/src/MaskEvent.c"
        "libx11/src/Misc.c"
        "libx11/src/ModMap.c"
        "libx11/src/MoveWin.c"
        "libx11/src/NextEvent.c"
        "libx11/src/OCWrap.c"
        "libx11/src/OMWrap.c"
        "libx11/src/OpenDis.c"
        "libx11/src/ParseCmd.c"
        "libx11/src/ParseCol.c"
        "libx11/src/ParseGeom.c"
        "libx11/src/PeekEvent.c"
        "libx11/src/PeekIfEv.c"
        "libx11/src/Pending.c"
        "libx11/src/PixFormats.c"
        "libx11/src/PmapBgnd.c"
        "libx11/src/PmapBord.c"
        "libx11/src/PolyReg.c"
        "libx11/src/PolyTxt16.c"
        "libx11/src/PolyTxt.c"
        "libx11/src/PropAlloc.c"
        "libx11/src/PutBEvent.c"
        "libx11/src/PutImage.c"
        "libx11/src/Quarks.c"
        "libx11/src/QuBest.c"
        "libx11/src/QuColor.c"
        "libx11/src/QuColors.c"
        "libx11/src/QuCurShp.c"
        "libx11/src/QuExt.c"
        "libx11/src/QuKeybd.c"
        "libx11/src/QuPntr.c"
        "libx11/src/QuStipShp.c"
        "libx11/src/QuTextE16.c"
        "libx11/src/QuTextExt.c"
        "libx11/src/QuTileShp.c"
        "libx11/src/QuTree.c"
        "libx11/src/RaiseWin.c"
        "libx11/src/RdBitF.c"
        "libx11/src/reallocarray.c"
        "libx11/src/RecolorC.c"
        "libx11/src/ReconfWin.c"
        "libx11/src/ReconfWM.c"
        "libx11/src/Region.c"
        "libx11/src/RegstFlt.c"
        "libx11/src/RepWindow.c"
        "libx11/src/RestackWs.c"
        "libx11/src/RotProp.c"
        "libx11/src/ScrResStr.c"
        "libx11/src/SelInput.c"
        "libx11/src/SendEvent.c"
        "libx11/src/SetBack.c"
        "libx11/src/SetClMask.c"
        "libx11/src/SetClOrig.c"
        "libx11/src/SetCRects.c"
        "libx11/src/SetDashes.c"
        "libx11/src/SetFont.c"
        "libx11/src/SetFore.c"
        "libx11/src/SetFPath.c"
        "libx11/src/SetFunc.c"
        "libx11/src/SetHints.c"
        "libx11/src/SetIFocus.c"
        "libx11/src/SetLocale.c"
        "libx11/src/SetLStyle.c"
        "libx11/src/SetNrmHint.c"
        "libx11/src/SetPMask.c"
        "libx11/src/SetPntMap.c"
        "libx11/src/SetRGBCMap.c"
        "libx11/src/SetSOwner.c"
        "libx11/src/SetSSaver.c"
        "libx11/src/SetState.c"
        "libx11/src/SetStCmap.c"
        "libx11/src/SetStip.c"
        "libx11/src/SetTile.c"
        "libx11/src/SetTSOrig.c"
        "libx11/src/SetTxtProp.c"
        "libx11/src/SetWMCMapW.c"
        "libx11/src/SetWMProto.c"
        "libx11/src/StBytes.c"
        "libx11/src/StColor.c"
        "libx11/src/StColors.c"
        "libx11/src/StName.c"
        "libx11/src/StNColor.c"
        "libx11/src/StrKeysym.c"
        "libx11/src/StrToText.c"
        "libx11/src/Sync.c"
        "libx11/src/Synchro.c"
        "libx11/src/Text16.c"
        "libx11/src/Text.c"
        "libx11/src/TextExt16.c"
        "libx11/src/TextExt.c"
        "libx11/src/TextToStr.c"
        "libx11/src/TrCoords.c"
        "libx11/src/UndefCurs.c"
        "libx11/src/UngrabBut.c"
        "libx11/src/UngrabKbd.c"
        "libx11/src/UngrabKey.c"
        "libx11/src/UngrabPtr.c"
        "libx11/src/UngrabSvr.c"
        "libx11/src/UninsCmap.c"
        "libx11/src/UnldFont.c"
        "libx11/src/UnmapSubs.c"
        "libx11/src/UnmapWin.c"
        "libx11/src/VisUtil.c"
        "libx11/src/WarpPtr.c"
        "libx11/src/Window.c"
        "libx11/src/WinEvent.c"
        "libx11/src/Withdraw.c"
        "libx11/src/WMGeom.c"
        "libx11/src/WMProps.c"
        "libx11/src/WrBitF.c"
        "libx11/src/xcb_disp.c"
        "libx11/src/xcb_io.c"
        "libx11/src/XlibAsync.c"
        "libx11/src/XlibInt.c"
        "libx11/src/Xrm.c"

        "libx11/src/xkb/XKB.c"
        "libx11/src/xkb/XKBBind.c"
        "libx11/src/xkb/XKBCompat.c"
        "libx11/src/xkb/XKBCtrls.c"
        "libx11/src/xkb/XKBCvt.c"
        "libx11/src/xkb/XKBGetMap.c"
        "libx11/src/xkb/XKBGetByName.c"
        "libx11/src/xkb/XKBNames.c"
        "libx11/src/xkb/XKBRdBuf.c"
        "libx11/src/xkb/XKBSetMap.c"
        "libx11/src/xkb/XKBUse.c"
        "libx11/src/xkb/XKBleds.c"
        "libx11/src/xkb/XKBBell.c"
        "libx11/src/xkb/XKBGeom.c"
        "libx11/src/xkb/XKBSetGeom.c"
        "libx11/src/xkb/XKBExtDev.c"
        "libx11/src/xkb/XKBList.c"
        "libx11/src/xkb/XKBMisc.c"
        "libx11/src/xkb/XKBMAlloc.c"
        "libx11/src/xkb/XKBGAlloc.c"
        "libx11/src/xkb/XKBAlloc.c"

        "libx11/src/xcms/AddDIC.c"
        "libx11/src/xcms/AddSF.c"
        "libx11/src/xcms/CCC.c"
        "libx11/src/xcms/CvColW.c"
        "libx11/src/xcms/CvCols.c"
        "libx11/src/xcms/HVC.c"
        "libx11/src/xcms/HVCGcC.c"
        "libx11/src/xcms/HVCGcV.c"
        "libx11/src/xcms/HVCGcVC.c"
        "libx11/src/xcms/HVCMnV.c"
        "libx11/src/xcms/HVCMxC.c"
        "libx11/src/xcms/HVCMxV.c"
        "libx11/src/xcms/HVCMxVC.c"
        "libx11/src/xcms/HVCMxVs.c"
        "libx11/src/xcms/HVCWpAj.c"
        "libx11/src/xcms/IdOfPr.c"
        "libx11/src/xcms/LRGB.c"
        "libx11/src/xcms/Lab.c"
        "libx11/src/xcms/LabGcC.c"
        "libx11/src/xcms/LabGcL.c"
        "libx11/src/xcms/LabGcLC.c"
        "libx11/src/xcms/LabMnL.c"
        "libx11/src/xcms/LabMxC.c"
        "libx11/src/xcms/LabMxL.c"
        "libx11/src/xcms/LabMxLC.c"
        "libx11/src/xcms/LabWpAj.c"
        "libx11/src/xcms/Luv.c"
        "libx11/src/xcms/LuvGcC.c"
        "libx11/src/xcms/LuvGcL.c"
        "libx11/src/xcms/LuvGcLC.c"
        "libx11/src/xcms/LuvMnL.c"
        "libx11/src/xcms/LuvMxC.c"
        "libx11/src/xcms/LuvMxL.c"
        "libx11/src/xcms/LuvMxLC.c"
        "libx11/src/xcms/LuvWpAj.c"
        "libx11/src/xcms/OfCCC.c"
        "libx11/src/xcms/PrOfId.c"
        "libx11/src/xcms/QBlack.c"
        "libx11/src/xcms/QBlue.c"
        "libx11/src/xcms/QGreen.c"
        "libx11/src/xcms/QRed.c"
        "libx11/src/xcms/QWhite.c"
        "libx11/src/xcms/QuCol.c"
        "libx11/src/xcms/QuCols.c"
        "libx11/src/xcms/SetCCC.c"
        "libx11/src/xcms/SetGetCols.c"
        "libx11/src/xcms/StCol.c"
        "libx11/src/xcms/StCols.c"
        "libx11/src/xcms/UNDEFINED.c"
        "libx11/src/xcms/XRGB.c"
        "libx11/src/xcms/XYZ.c"
        "libx11/src/xcms/cmsAllCol.c"
        "libx11/src/xcms/cmsAllNCol.c"
        "libx11/src/xcms/cmsCmap.c"
        "libx11/src/xcms/cmsColNm.c"
        "libx11/src/xcms/cmsGlobls.c"
        "libx11/src/xcms/cmsInt.c"
        "libx11/src/xcms/cmsLkCol.c"
        "libx11/src/xcms/cmsMath.c"
        "libx11/src/xcms/cmsProp.c"
        "libx11/src/xcms/cmsTrig.c"
        "libx11/src/xcms/uvY.c"
        "libx11/src/xcms/xyY.c"

        "libx11/src/xlibi18n/XlcDL.c"
        "libx11/src/xlibi18n/XlcSL.c"
        "libx11/src/xlibi18n/XDefaultIMIF.c"
        "libx11/src/xlibi18n/XDefaultOMIF.c"
        "libx11/src/xlibi18n/xim_trans.c"
        "libx11/src/xlibi18n/ICWrap.c"
        "libx11/src/xlibi18n/IMWrap.c"
        "libx11/src/xlibi18n/imKStoUCS.c"
        "libx11/src/xlibi18n/lcCT.c"
        "libx11/src/xlibi18n/lcCharSet.c"
        "libx11/src/xlibi18n/lcConv.c"
        "libx11/src/xlibi18n/lcDB.c"
        "libx11/src/xlibi18n/lcDynamic.c"
        "libx11/src/xlibi18n/lcFile.c"
        "libx11/src/xlibi18n/lcGeneric.c"
        "libx11/src/xlibi18n/lcInit.c"
        "libx11/src/xlibi18n/lcPrTxt.c"
        "libx11/src/xlibi18n/lcPubWrap.c"
        "libx11/src/xlibi18n/lcPublic.c"
        "libx11/src/xlibi18n/lcRM.c"
        "libx11/src/xlibi18n/lcStd.c"
        "libx11/src/xlibi18n/lcTxtPr.c"
        "libx11/src/xlibi18n/lcUTF8.c"
        "libx11/src/xlibi18n/lcUtil.c"
        "libx11/src/xlibi18n/lcWrap.c"
        "libx11/src/xlibi18n/mbWMProps.c"
        "libx11/src/xlibi18n/mbWrap.c"
        "libx11/src/xlibi18n/utf8WMProps.c"
        "libx11/src/xlibi18n/utf8Wrap.c"
        "libx11/src/xlibi18n/wcWrap.c"

        "libx11/modules/im/ximcp/imCallbk.c"
        "libx11/modules/im/ximcp/imDefFlt.c"
        "libx11/modules/im/ximcp/imDefIc.c"
        "libx11/modules/im/ximcp/imDefIm.c"
        "libx11/modules/im/ximcp/imDefLkup.c"
        "libx11/modules/im/ximcp/imDispch.c"
        "libx11/modules/im/ximcp/imEvToWire.c"
        "libx11/modules/im/ximcp/imExten.c"
        "libx11/modules/im/ximcp/imImSw.c"
        "libx11/modules/im/ximcp/imInsClbk.c"
        "libx11/modules/im/ximcp/imInt.c"
        "libx11/modules/im/ximcp/imLcFlt.c"
        "libx11/modules/im/ximcp/imLcGIc.c"
        "libx11/modules/im/ximcp/imLcIc.c"
        "libx11/modules/im/ximcp/imLcIm.c"
        "libx11/modules/im/ximcp/imLcLkup.c"
        "libx11/modules/im/ximcp/imLcPrs.c"
        "libx11/modules/im/ximcp/imLcSIc.c"
        "libx11/modules/im/ximcp/imRmAttr.c"
        "libx11/modules/im/ximcp/imRm.c"
        "libx11/modules/im/ximcp/imThaiFlt.c"
        "libx11/modules/im/ximcp/imThaiIc.c"
        "libx11/modules/im/ximcp/imThaiIm.c"
        "libx11/modules/im/ximcp/imTrans.c"
        "libx11/modules/im/ximcp/imTransR.c"
        "libx11/modules/im/ximcp/imTrX.c"

        "libx11/modules/lc/def/lcDefConv.c"
        "libx11/modules/lc/gen/lcGenConv.c"
        "libx11/modules/lc/Utf8/lcUTF8Load.c"

        "libx11/modules/om/generic/omDefault.c"
        "libx11/modules/om/generic/omGeneric.c"
        "libx11/modules/om/generic/omImText.c"
        "libx11/modules/om/generic/omText.c"
        "libx11/modules/om/generic/omTextEsc.c"
        "libx11/modules/om/generic/omTextExt.c"
        "libx11/modules/om/generic/omTextPer.c"
        "libx11/modules/om/generic/omXChar.c")
target_link_libraries(X11 PUBLIC Xtrans xcb xcbproto)
target_link_options(X11 PRIVATE "-fPIC")
target_include_directories(X11
        PUBLIC
        "libx11/include"
        PRIVATE
        "libx11/include/X11"
        "libx11/src"
        "libx11/src/xcms"
        "libx11/src/xlibi18n"
        "libx11/src/xkb"
        "${CMAKE_CURRENT_BINARY_DIR}"
        "${CMAKE_CURRENT_BINARY_DIR}/X11")
target_compile_options(X11 PRIVATE ${common_compile_options} "-fvisibility=hidden" "-D_DEFAULT_SOURCE" "-D_BSD_SOURCE" "-DHAS_FCHOWN" "-DHAS_STICKY_DIR_BIT" "-DHAVE_CONFIG_H" "-D_GNU_SOURCE=1" "-DXCMSDIR=\"/\"" "-fPIE" "-fPIC")

add_library(X11-xcb STATIC "libx11/src/x11_xcb.c")
target_include_directories(X11-xcb PRIVATE
        "${CMAKE_CURRENT_BINARY_DIR}"
        "${CMAKE_CURRENT_BINARY_DIR}/xcb"
        "xorgproto/include"
        "libx11/include"
        "libx11/include/X11")
target_link_libraries(X11-xcb PRIVATE xcb)